In [3]:
import pandas as pd
import numpy as np
from scipy.stats import pearsonr

In [4]:
# loading my  data
df = pd.read_csv('../data/clean/clean_data.csv')

# creating a filter for players that were transferred for a fee of 3million euros and above.

In [5]:
data = df.loc[(df['fees_paid_for_player'] >= 3)]

In [6]:
data

,name,position,age,market_value,country_playing,current_league,club,country_moving_to,new_league,club_moving_to,fees_paid_for_player,on_loan
0,Erling Haaland,Forward,21,150,Germany,Bundesliga,Borussia Dortmund,England,Premier League,Manchester City,60,No
1,Antony,Forward,22,35,Netherlands,Eredivisie,Ajax Amsterdam,England,Premier League,Manchester United,95,No
2,Wesley Fofana,Defence,21,40,England,Premier League,Leicester City,England,Premier League,Chelsea FC,80,No
3,Aurélien Tchouameni,Midfield,22,60,Monaco,Ligue 1,AS Monaco,Spain,LaLiga,Real Madrid,80,No
4,Darwin Núñez,Forward,23,55,Portugal,Liga Portugal,SL Benfica,England,Premier League,Liverpool FC,75,No
...,...,...,...,...,...,...,...,...,...,...,...,...
1022,Alex Santana,Midfield,27,2,Bulgaria,efbet Liga,Ludogorets Razgrad,Brazil,Série A,Club Athletico Paranaense,3,No
1023,Joel Pohjanpalo,Forward,27,3,Germany,Bundesliga,Bayer 04 Leverkusen,Italy,Serie B,Venezia FC,3,No
1151,Wilfried Kanga,Forward,24,2,Switzerland,Super League,BSC Young Boys,Germany,Bundesliga,Hertha BSC,4,No
1179,Jordy Caicedo,Forward,24,2,Bulgaria,efbet Liga,CSKA-Sofia,Mexico,Liga MX Apertura,Tigres UANL,3,No
1485,Marcelino Núñez,Midfield,22,2,Chile,Primera División,CD Universidad Católica,England,Championship,Norwich City,4,No

In [7]:
# extracting the columns of interest
market_value = data['market_value']
fees_paid_for_player = data['fees_paid_for_player']

# compute the Pearson correlation coefficient and p-value
corr, p_value = pearsonr(market_value, fees_paid_for_player)

# print the correlation coefficient and p-value
print(f"Correlation Coefficient: {corr:.4f}")
print(f"P-value: {p_value:.4f}")

# perform the hypothesis test at the 5% significance level
alpha = 0.05
if p_value < alpha:
    print("Reject the null hypothesis. There is a significant correlation between market_value and fees_paid_for_player.")
else:
    print("Fail to reject the null hypothesis. There is no significant correlation between market_value and fees_paid_for_player.")

Correlation Coefficient: 0.7569
P-value: 0.0000
Reject the null hypothesis. There is a significant correlation between market_value and fees_paid_for_player.